// <!-- START OF FILE: main-action-generator.test.js -->
// FILENAME: main-action-generator.test.js
// Version: 1.0.0
// Date: 2025-07-30 16:30
// Author: Rolland MELET & Claude Code
// Description: Tests unitaires MainActionGenerator - TASK-B006

/**
 * Tests unitaires pour le module MainActionGenerator
 * Validation complète de la génération automatique des actions principales
 * selon l'architecture État-Actions deux niveaux ProcessMetaLanguage
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { MainActionGenerator, MAIN_ACTION_CONFIG } from '../../core/main-action-generator.js';

describe('MainActionGenerator', () => {
    let generator;
    let mockStateData;
    let mockObjectData;

    beforeEach(() => {
        generator = new MainActionGenerator();
        
        mockStateData = {
            stateId: 'state_test_001',
            stateName: 'En_Test',
            disposition: 'active',
            businessStep: 'testing',
            position: { x: 100, y: 200 },
            createdAt: '2025-07-30T16:30:00.000Z',
            userMetadata: {
                businessStep: 'testing',
                businessLocation: 'urn:epc:id:sgln:0000001.00001.0'
            }
        };

        mockObjectData = {
            objectId: 'obj_test_001',
            objectName: 'Objet Test A001',
            objectType: 'raw-material',
            epc: 'urn:epc:id:sgtin:0000001.000001.000001',
            position: { x: 50, y: 150 },
            createdAt: '2025-07-30T16:00:00.000Z',
            userMetadata: {
                company: '0000001',
                product: '000001',
                serial: '000001',
                avatarId: 'avatar_test_001'
            }
        };
    });

    afterEach(() => {
        vi.clearAllMocks();
    });

    describe('Configuration et initialisation', () => {
        it('devrait initialiser avec configuration par défaut', () => {
            expect(generator.config.actionType).toBe('main_action');
            expect(generator.config.actionCategory).toBe('data_exposition');
            expect(generator.config.cacheEnabled).toBe(true);
        });

        it('devrait permettre override configuration', () => {
            const customGenerator = new MainActionGenerator({
                cacheEnabled: false,
                maxGenerationTime: 2000
            });
            
            expect(customGenerator.config.cacheEnabled).toBe(false);
            expect(customGenerator.config.maxGenerationTime).toBe(2000);
            expect(customGenerator.config.actionType).toBe('main_action'); // Garde défaut
        });

        it('devrait initialiser statistiques à zéro', () => {
            expect(generator.stats.actionsGenerated).toBe(0);
            expect(generator.stats.averageGenerationTime).toBe(0);
            expect(generator.stats.cacheHits).toBe(0);
        });
    });

    describe('generateMainAction()', () => {
        it('devrait générer action principale complète', async () => {
            const action = await generator.generateMainAction(mockStateData, mockObjectData);

            // Validation structure de base
            expect(action).toHaveProperty('id');
            expect(action).toHaveProperty('name');
            expect(action).toHaveProperty('description');
            expect(action).toHaveProperty('type', 'main_action');
            expect(action).toHaveProperty('category', 'data_exposition');
            expect(action.generated).toBe(true);
            expect(action.autoGenerated).toBe(true);
        });

        it('devrait générer nom action selon pattern', async () => {
            const action = await generator.generateMainAction(mockStateData, mockObjectData);
            
            expect(action.name).toBe('Consulter État En_Test');
            expect(action.description).toContain('exposition complète des données');
            expect(action.description).toContain('En_Test');
        });

        it('devrait inclure relations hiérarchiques correctes', async () => {
            const action = await generator.generateMainAction(mockStateData, mockObjectData);
            
            expect(action.parentStateId).toBe(mockStateData.stateId);
            expect(action.parentStateName).toBe(mockStateData.stateName);
            expect(action.parentObjectId).toBe(mockObjectData.objectId);
            expect(action.parentObjectName).toBe(mockObjectData.objectName);
        });

        it('devrait générer métadonnées EPCIS 2.0 conformes', async () => {
            const action = await generator.generateMainAction(mockStateData, mockObjectData);
            
            expect(action.epcisMetadata).toHaveProperty('eventType', 'ObjectEvent');
            expect(action.epcisMetadata).toHaveProperty('businessStep', 'observing');
            expect(action.epcisMetadata).toHaveProperty('disposition', mockStateData.disposition);
            expect(action.epcisMetadata).toHaveProperty('cbvCompliant', true);
            expect(action.epcisMetadata).toHaveProperty('cbvVersion', '2.0.0');
        });

        it('devrait inclure spécifications API OpenAPI 3.0', async () => {
            const action = await generator.generateMainAction(mockStateData, mockObjectData);
            
            expect(action.apiSpecifications).toHaveProperty('openapi', '3.0.0');
            expect(action.apiSpecifications).toHaveProperty('info');
            expect(action.apiSpecifications).toHaveProperty('paths');
            expect(action.apiSpecifications.info.title).toContain(action.name);
        });

        it('devrait exposer données via DataExposer', async () => {
            const action = await generator.generateMainAction(mockStateData, mockObjectData);
            
            expect(action.exposedData).toBeDefined();
            expect(typeof action.exposedData).toBe('object');
        });

        it('devrait construire navigation via NavigationBuilder', async () => {
            const action = await generator.generateMainAction(mockStateData, mockObjectData);
            
            expect(action.navigation).toBeDefined();
            expect(typeof action.navigation).toBe('object');
        });

        it('devrait calculer position action relative à état', async () => {
            const action = await generator.generateMainAction(mockStateData, mockObjectData);
            
            expect(action.position.x).toBe(mockStateData.position.x + 100);
            expect(action.position.y).toBe(mockStateData.position.y);
            expect(action.position.relative).toBe(true);
            expect(action.position.anchor).toBe('state');
        });
    });

    describe('Validation données entrée', () => {
        it('devrait valider données état requises', async () => {
            const invalidStateData = { /* manque stateId et stateName */ };
            
            await expect(
                generator.generateMainAction(invalidStateData, mockObjectData)
            ).rejects.toThrow('Champ requis manquant dans données état: stateId');
        });

        it('devrait valider données objet requises', async () => {
            const invalidObjectData = { objectId: 'test' /* manque objectName */ };
            
            await expect(
                generator.generateMainAction(mockStateData, invalidObjectData)
            ).rejects.toThrow('Champ requis manquant dans données objet: objectName');
        });

        it('devrait rejeter données null ou undefined', async () => {
            await expect(
                generator.generateMainAction(null, mockObjectData)
            ).rejects.toThrow('Données état manquantes ou invalides');

            await expect(
                generator.generateMainAction(mockStateData, null)
            ).rejects.toThrow('Données objet manquantes ou invalides');
        });
    });

    describe('Cache et performance', () => {
        it('devrait utiliser cache pour actions identiques', async () => {
            // Première génération
            const action1 = await generator.generateMainAction(mockStateData, mockObjectData);
            expect(generator.stats.cacheMisses).toBe(1);
            expect(generator.stats.cacheHits).toBe(0);

            // Deuxième génération identique - doit utiliser cache
            const action2 = await generator.generateMainAction(mockStateData, mockObjectData);
            expect(generator.stats.cacheHits).toBe(1);
            expect(action1.id).toBe(action2.id);
        });

        it('devrait invalider cache après TTL', async () => {
            // Configuration avec TTL court pour test
            const fastGenerator = new MainActionGenerator({ cacheTTL: 10 });
            
            await fastGenerator.generateMainAction(mockStateData, mockObjectData);
            expect(fastGenerator.stats.cacheMisses).toBe(1);
            
            // Attendre expiration cache
            await new Promise(resolve => setTimeout(resolve, 15));
            
            await fastGenerator.generateMainAction(mockStateData, mockObjectData);
            expect(fastGenerator.stats.cacheMisses).toBe(2); // Cache expiré
        });

        it('devrait respecter target temps génération', async () => {
            const startTime = performance.now();
            await generator.generateMainAction(mockStateData, mockObjectData);
            const executionTime = performance.now() - startTime;
            
            expect(executionTime).toBeLessThan(generator.config.maxGenerationTime);
        });

        it('devrait mettre à jour statistiques correctement', async () => {
            const initialStats = { ...generator.stats };
            
            await generator.generateMainAction(mockStateData, mockObjectData);
            
            expect(generator.stats.actionsGenerated).toBe(initialStats.actionsGenerated + 1);
            expect(generator.stats.averageGenerationTime).toBeGreaterThan(0);
        });
    });

    describe('generateMainActionsBatch()', () => {
        it('devrait traiter batch actions en parallèle', async () => {
            const statesData = [
                { ...mockStateData, stateId: 'state_1', stateName: 'État_1' },
                { ...mockStateData, stateId: 'state_2', stateName: 'État_2' },
                { ...mockStateData, stateId: 'state_3', stateName: 'État_3' }
            ];
            
            const objectsData = [
                { ...mockObjectData, objectId: 'obj_1', objectName: 'Objet_1' },
                { ...mockObjectData, objectId: 'obj_2', objectName: 'Objet_2' },
                { ...mockObjectData, objectId: 'obj_3', objectName: 'Objet_3' }
            ];
            
            const results = await generator.generateMainActionsBatch(statesData, objectsData);
            
            expect(results.totalStates).toBe(3);
            expect(results.successful).toBe(3);
            expect(results.failed).toBe(0);
            expect(results.results).toHaveLength(3);
            expect(results.performanceTarget).toContain('✅');
        });

        it('devrait gérer erreurs batch sans arrêter traitement', async () => {
            const statesData = [
                { ...mockStateData, stateId: 'state_valid' },
                { /* état invalide sans champs requis */ },
                { ...mockStateData, stateId: 'state_valid_2' }
            ];
            
            const objectsData = [
                { ...mockObjectData, objectId: 'obj_1' },
                { ...mockObjectData, objectId: 'obj_2' },
                { ...mockObjectData, objectId: 'obj_3' }
            ];
            
            const results = await generator.generateMainActionsBatch(statesData, objectsData);
            
            expect(results.successful).toBe(2); // 2 valides sur 3
            expect(results.failed).toBe(1);     // 1 échec
            expect(results.results).toHaveLength(3);
        });

        it('devrait respecter target performance 5s pour 50 actions', async () => {
            // Générer 50 états/objets de test
            const statesData = Array.from({ length: 50 }, (_, i) => ({
                ...mockStateData,
                stateId: `state_batch_${i}`,
                stateName: `État_Batch_${i}`
            }));
            
            const objectsData = Array.from({ length: 50 }, (_, i) => ({
                ...mockObjectData,
                objectId: `obj_batch_${i}`,
                objectName: `Objet_Batch_${i}`
            }));
            
            const startTime = performance.now();
            const results = await generator.generateMainActionsBatch(statesData, objectsData);
            const totalTime = performance.now() - startTime;
            
            expect(results.successful).toBe(50);
            expect(totalTime).toBeLessThan(5000); // < 5s pour 50 actions
            expect(results.performanceTarget).toContain('✅');
        });
    });

    describe('updateMainAction()', () => {
        it('devrait mettre à jour action avec nouvelles données état', async () => {
            // Générer action initiale
            const initialAction = await generator.generateMainAction(mockStateData, mockObjectData);
            
            // Mettre à jour état
            const updatedStateData = {
                ...mockStateData,
                stateName: 'État_Modifié',
                disposition: 'in_progress'
            };
            
            const updatedAction = await generator.updateMainAction(updatedStateData, mockObjectData);
            
            expect(updatedAction.name).toBe('Consulter État État_Modifié');
            expect(updatedAction.epcisMetadata.disposition).toBe('in_progress');
            expect(updatedAction.id).not.toBe(initialAction.id); // Nouvel ID généré
        });

        it('devrait invalider cache lors mise à jour', async () => {
            await generator.generateMainAction(mockStateData, mockObjectData);
            expect(generator.stats.cacheHits).toBe(0);
            
            // Cache hit sur même données
            await generator.generateMainAction(mockStateData, mockObjectData);
            expect(generator.stats.cacheHits).toBe(1);
            
            // Mise à jour invalide cache
            const updatedStateData = { ...mockStateData, stateName: 'Modifié' };
            await generator.updateMainAction(updatedStateData, mockObjectData);
            
            // Nouvelle génération - cache miss car invalidé
            await generator.generateMainAction(updatedStateData, mockObjectData);
            expect(generator.stats.cacheMisses).toBeGreaterThan(1);
        });
    });

    describe('Génération EPC et métadonnées', () => {
        it('devrait générer EPC SGTIN valide', async () => {
            const action = await generator.generateMainAction(mockStateData, mockObjectData);
            
            const epc = action.epcisMetadata.epcList[0];
            expect(epc).toMatch(/^urn:epc:id:sgtin:\d+\.\d+\.\d+$/);
            expect(epc).toContain('0000001.000001.000001');
        });

        it('devrait utiliser EPC existant si fourni', async () => {
            const objectDataWithEPC = {
                ...mockObjectData,
                epc: 'urn:epc:id:sgtin:1234567.890123.456789'
            };
            
            const action = await generator.generateMainAction(mockStateData, objectDataWithEPC);
            
            expect(action.epcisMetadata.epcList[0]).toBe('urn:epc:id:sgtin:1234567.890123.456789');
        });
    });

    describe('Validation action générée', () => {
        it('devrait valider structure action complète', async () => {
            const action = await generator.generateMainAction(mockStateData, mockObjectData);
            
            // Champs requis présents
            const requiredFields = [
                'id', 'name', 'description', 'type', 'category',
                'parentStateId', 'parentObjectId', 'exposedData', 
                'navigation', 'epcisMetadata', 'apiSpecifications'
            ];
            
            requiredFields.forEach(field => {
                expect(action).toHaveProperty(field);
                expect(action[field]).not.toBeNull();
                expect(action[field]).not.toBeUndefined();
            });
        });

        it('devrait rejeter action avec champs manquants', async () => {
            // Mock DataExposer qui retourne null
            vi.spyOn(generator.dataExposer, 'exposeCompleteStateData').mockResolvedValue(null);
            
            await expect(
                generator.generateMainAction(mockStateData, mockObjectData)
            ).rejects.toThrow('Données exposées manquantes ou invalides');
        });
    });

    describe('getPerformanceStats()', () => {
        it('devrait retourner statistiques performance', async () => {
            await generator.generateMainAction(mockStateData, mockObjectData);
            
            const stats = generator.getPerformanceStats();
            
            expect(stats).toHaveProperty('actionsGenerated', 1);
            expect(stats).toHaveProperty('averageGenerationTime');
            expect(stats).toHaveProperty('cacheStats');
            expect(stats).toHaveProperty('performanceTarget');
            expect(stats.averageGenerationTime).toBeGreaterThan(0);
        });

        it('devrait calculer ratio cache correctement', async () => {
            // Générer pour avoir cache miss
            await generator.generateMainAction(mockStateData, mockObjectData);
            // Générer pour avoir cache hit
            await generator.generateMainAction(mockStateData, mockObjectData);
            
            const stats = generator.getPerformanceStats();
            
            expect(stats.cacheStats.hits).toBe(1);
            expect(stats.cacheStats.misses).toBe(1);
            expect(stats.cacheStats.hitRatio).toBe(50);
        });
    });

    describe('reset()', () => {
        it('devrait remettre à zéro cache et statistiques', async () => {
            // Générer quelques actions
            await generator.generateMainAction(mockStateData, mockObjectData);
            await generator.generateMainAction({...mockStateData, stateId: 'state_2'}, mockObjectData);
            
            expect(generator.stats.actionsGenerated).toBeGreaterThan(0);
            expect(generator.actionCache.size).toBeGreaterThan(0);
            
            generator.reset();
            
            expect(generator.stats.actionsGenerated).toBe(0);
            expect(generator.stats.averageGenerationTime).toBe(0);
            expect(generator.actionCache.size).toBe(0);
        });
    });

    describe('Gestion erreurs', () => {
        it('devrait enregistrer erreurs dans statistiques', async () => {
            const initialErrorsCount = generator.stats.errors.length;
            
            try {
                await generator.generateMainAction(null, mockObjectData);
            } catch (error) {
                // Erreur attendue
            }
            
            expect(generator.stats.errors.length).toBe(initialErrorsCount + 1);
            expect(generator.stats.errors[initialErrorsCount]).toHaveProperty('error');
            expect(generator.stats.errors[initialErrorsCount]).toHaveProperty('timestamp');
        });

        it('devrait propager erreurs validation EPCIS', async () => {
            // Mock EPCISValidator qui retourne erreur
            vi.spyOn(generator.dataExposer.epcisValidator, 'validateTemplate').mockResolvedValue({
                isValid: false,
                errors: ['Test error']
            });
            
            await expect(
                generator.generateMainAction(mockStateData, mockObjectData)
            ).rejects.toThrow('Template non conforme EPCIS 2.0');
        });
    });
});

// <!-- END OF FILE: main-action-generator.test.js -->